image: docker:20.10

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - preprod
  - integration
  - prod

job:
  stage: build
  script:
    - echo "I'm a job"
oast:
  runs-on: ubuntu-20.04
  needs: test
  steps:
    - uses: actions/checkout@v2

    - run: docker run --rm -v $(pwd):/src hysnsec/safety check -r requirements.txt --json > oast-results.json

    - uses: actions/upload-artifact@v2
      with:
        name: Safety
        path: oast-results.json
      if: always()                        # what is this for?
